# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e605b0857594f485855f4ab8735ad4b1b328e6d2a3abdc3be20d3399551007173cac0114d5211188bed74352a2bd10ee5759555bdc00a1a74da7f58576ea46cb

test:
  secret_key_base: 8373940161c16dcb7dcafe0f6f3c96c5a603a47039421abe6978dc4fc65cee83ecefebf5bd4cb861b15d3345befef8672aea387879ba09a7d5d2846c0a757e53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
